source 'http://rubygems.org'

gem 'rails', '3.0.3'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'sqlite3-ruby', :require => 'sqlite3'

gem 'devise', "1.2.rc"
gem 'devise_paypal', :path => "/home/dave/work/plugins/devise_paypal"
gem 'paypal-ipn'

group :test do
  gem 'cucumber-rails'
  gem 'capybara'
  gem 'pickle'
  gem 'fakeweb'
end

