source 'http://rubygems.org'

gem 'rails', '3.0.1'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'sqlite3-ruby', :require => 'sqlite3'

gem 'devise', "1.2.rc"
gem 'devise_paypal', :git => 'git://github.com/dwilkie/devise_paypal.git'
gem 'paypal-ipn', :require => 'paypal', :git => 'git://github.com/dwilkie/paypal.git'

group :test do
  gem 'cucumber-rails'
  gem 'capybara'
  gem 'pickle'
  gem 'fakeweb'
  gem 'ruby-debug19'
end

